"""
test_api.py

Run with: python3 test_api.py   (from inside backend/api)

The full session lifecycle against a throwaway database:

    signup -> login -> create session -> link calibration (trains a real
    gaze model) -> post gaze -> finalize -> fetch report

Plus the ownership boundary, which is the part worth being paranoid about:
two users are created and every session route is probed across them.

Nothing here needs a webcam or the real detector weights. The calibration
session is generated by gaze_estimation's synthetic module, so the gaze model
is genuinely trained; the gaze stream is scripted by attribution's synthetic
module, so the metrics have known ground truth.

Same shape as backend/agents/test_agents.py: flat script, check() counter,
non-zero exit on failure.
"""

import asyncio
import os
import shutil
import sys
import tempfile
import warnings
from pathlib import Path

# backend/ on the path so sibling packages import by name, and this file can
# be run directly the way test_agents.py is.
BACKEND = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(BACKEND))

# Must be set before api.db is imported -- it reads these at module scope.
_TMP = Path(tempfile.mkdtemp(prefix="gazelens_api_test_"))
os.environ["GAZELENS_DATABASE_URL"] = f"sqlite:///{(_TMP / 'test.db').as_posix()}"
os.environ["GAZELENS_DATA_DIR"] = str(_TMP / "data")
# >=32 bytes: PyJWT warns below that for HS256 (RFC 7518 §3.2), and a warning
# on every run trains people to ignore warnings.
os.environ.setdefault(
    "GAZELENS_SECRET_KEY",
    "test-only-key-not-for-deployment-0123456789abcdef",
)

from fastapi import HTTPException                                  # noqa: E402

from api import pipeline, session_routes                           # noqa: E402
from api.auth_routes import login, me, signup                      # noqa: E402
from api.db import DATA_DIR, SessionLocal, init_db                 # noqa: E402
from api.deps import get_current_user                              # noqa: E402
from api.models import STATUS_COMPLETE, Report, Session as SessionModel, User  # noqa: E402
from api.schemas import (                                          # noqa: E402
    CalibrationLinkRequest,
    CreateSessionRequest,
    GazeBatchRequest,
    LoginRequest,
    SignupRequest,
)
from api.security import create_access_token, hash_password, verify_password  # noqa: E402

passed = 0
failed = 0


def check(label, condition):
    global passed, failed
    if condition:
        print(f"  PASS  {label}")
        passed += 1
    else:
        print(f"  FAIL  {label}")
        failed += 1


def run(coro):
    return asyncio.run(coro)


def expect_http(label, target, status_code):
    """Assert an HTTPException. Accepts a coroutine or a zero-arg callable.

    The route handlers are async but the dependencies (get_current_user) are
    sync, so both forms turn up -- a sync one raises before this function is
    even entered unless it's wrapped in a lambda.
    """
    try:
        run(target) if asyncio.iscoroutine(target) else target()
    except HTTPException as exc:
        check(f"{label} -> {status_code}", exc.status_code == status_code)
        return
    check(f"{label} -> {status_code}", False)


class _Background:
    """Stand-in for FastAPI's BackgroundTasks that runs the task immediately.

    The route schedules analysis in the background so the request can return
    before a multi-second Chromium PDF render. Running it inline here makes
    the test deterministic instead of racing a real background thread.
    """

    def __init__(self):
        self.ran = []

    def add_task(self, fn, *args, **kwargs):
        self.ran.append(fn.__name__)
        fn(*args, **kwargs)


def db_session():
    return SessionLocal()


try:
    init_db(drop=True)

    # ------------------------------------------------------------------
    print("security -- password hashing and JWT")
    h = hash_password("correct-horse-battery")
    check("bcrypt hash isn't the password", h != "correct-horse-battery")
    check("correct password verifies", verify_password("correct-horse-battery", h))
    check("wrong password rejected", not verify_password("wrong", h))
    check("a corrupt stored hash reads as wrong, not a crash",
          verify_password("x", "not-a-bcrypt-hash") is False)

    from api.security import PasswordError, decode_access_token, validate_password

    for bad, why in (("short", "too short"), ("x" * 100, "over bcrypt's 72 bytes")):
        try:
            validate_password(bad)
            check(f"rejects a password {why}", False)
        except PasswordError:
            check(f"rejects a password {why}", True)

    token = create_access_token("usr_abc")
    check("token round-trips to its subject", decode_access_token(token) == "usr_abc")
    check("garbage token returns None, not an exception",
          decode_access_token("not.a.token") is None)
    check("token signed with another key is rejected",
          decode_access_token(
              __import__("jwt").encode({"sub": "usr_abc"}, "other-key", algorithm="HS256")
          ) is None)
    check("an expired token is rejected",
          decode_access_token(create_access_token("usr_abc", ttl_minutes=-1)) is None)

    # ------------------------------------------------------------------
    print("\nauth -- signup and login")
    db = db_session()
    alice = run(signup(SignupRequest(email="Alice@Example.com",
                                     password="alice-password-1"), db))
    check("signup returns a bearer token", alice.token_type == "bearer")
    check("signup returns the user", alice.user.email == "alice@example.com")
    check("email is normalised to lowercase", alice.user.email == "alice@example.com")

    bob = run(signup(SignupRequest(email="bob@example.com",
                                   password="bob-password-1"), db))
    check("second user created", bob.user.id != alice.user.id)

    expect_http("duplicate email",
                signup(SignupRequest(email="alice@example.com",
                                     password="another-password"), db), 409)
    expect_http("duplicate email in different case",
                signup(SignupRequest(email="ALICE@example.com",
                                     password="another-password"), db), 409)

    relogin = run(login(LoginRequest(email="alice@example.com",
                                     password="alice-password-1"), db))
    check("login works", relogin.user.id == alice.user.id)
    expect_http("login with wrong password",
                login(LoginRequest(email="alice@example.com", password="nope"), db), 401)
    expect_http("login for a nonexistent account",
                login(LoginRequest(email="ghost@example.com",
                                   password="whatever-1"), db), 401)

    print("\nauth -- addresses the API will actually accept")
    # EmailStr rejects special-use/reserved domains. This caught a real bug:
    # init_db --demo-user used to create demo@gazelens.local, which meant the
    # demo account could never log in -- /api/auth/login 422s on the address
    # before it ever checks the password.
    from pydantic import ValidationError

    for bad in ("demo@gazelens.local", "user@localhost", "not-an-email"):
        try:
            SignupRequest(email=bad, password="whatever-123")
            check(f"rejects {bad}", False)
        except ValidationError:
            check(f"rejects {bad}", True)

    from api.init_db import main as init_db_main  # noqa: F401 -- import check

    import inspect

    import api.init_db as init_db_mod

    demo_emails = [
        line.split('"')[1]
        for line in inspect.getsource(init_db_mod).splitlines()
        if "email = " in line and '"' in line
    ]
    check("the demo account's address is one the API accepts",
          bool(demo_emails) and all(
              SignupRequest(email=e, password="demo-password-123") for e in demo_emails))

    alice_user = db.get(User, alice.user.id)
    bob_user = db.get(User, bob.user.id)
    check("GET /me returns the caller", run(me(alice_user)).id == alice.user.id)

    print("\nauth -- the dependency rejects bad credentials")
    expect_http("no token", lambda: get_current_user(None, db), 401)
    expect_http("malformed token", lambda: get_current_user("garbage", db), 401)
    expect_http("token for a deleted user",
                lambda: get_current_user(create_access_token("usr_gone"), db), 401)
    check("valid token resolves to the user",
          get_current_user(alice.access_token, db).id == alice.user.id)

    # ------------------------------------------------------------------
    print("\nsessions -- creation and validation")
    created = run(session_routes.create_session(
        CreateSessionRequest(mode="test_ui", ui_page="ecommerce_product_page",
                             label="Alice run 1"),
        alice_user, db))
    session_id = created.id
    check("session created", session_id.startswith("ses_"))
    check("status starts at created", created.status == "created")
    check("no report yet", created.has_report is False)
    check("test_ui layout is not a placeholder", created.layout_is_placeholder is False)

    for req, why in (
        (CreateSessionRequest(mode="test_ui"), "test_ui without ui_page"),
        (CreateSessionRequest(mode="test_ui", ui_page="no_such_page"), "unknown ui_page"),
        (CreateSessionRequest(mode="url"), "url mode without target_url"),
    ):
        expect_http(why, session_routes.create_session(req, alice_user, db), 422)

    print("\nsessions -- url mode captures the page via backend/render")
    # capture_page is patched rather than hitting a live site: a test that
    # depends on example.com fails whenever that page or the network changes.
    # backend/render/test_render.py exercises the real capture against a local
    # fixture; what matters here is that the session layer wires both outcomes
    # up correctly.
    _real_capture = pipeline.capture_page

    def _fake_capture_ok(target_url, **kw):
        return {
            "ok": True, "target_url": target_url, "final_url": target_url,
            "title": "Captured Page", "detected": 12, "kept": 4,
            "low_confidence_fraction": 0.25,
            "screenshot_path": None, "classification": {}, "warnings": [],
            "layout": {
                "hero": {"bbox": (0.05, 0.10, 0.50, 0.40),
                         "importance": "medium", "type": "image"},
                "headline": {"bbox": (0.60, 0.10, 0.35, 0.12),
                             "importance": "medium", "type": "text"},
                "signup_button": {"bbox": (0.60, 0.30, 0.25, 0.10),
                                  "importance": "high", "type": "CTA"},
                "site_nav": {"bbox": (0.00, 0.00, 1.00, 0.07),
                             "importance": "low", "type": "nav"},
            },
        }

    def _fake_capture_fail(target_url, **kw):
        return {"ok": False, "layout": {}, "target_url": target_url,
                "reason": "TimeoutError: page never loaded"}

    pipeline.capture_page = _fake_capture_ok
    url_session = run(session_routes.create_session(
        CreateSessionRequest(mode="url", target_url="https://example.com"),
        alice_user, db))
    check("url session created", url_session.mode == "url")
    check("a successful capture is NOT a placeholder",
          url_session.layout_is_placeholder is False)
    url_detail = run(session_routes.get_session(url_session.id, alice_user, db))
    check("detected elements became the session layout",
          set(url_detail.element_layout) == {"hero", "headline",
                                             "signup_button", "site_nav"})
    check("capture metadata recorded",
          url_detail.capture_meta["kept"] == 4)
    check("detection confidence recorded",
          url_detail.capture_meta["low_confidence_fraction"] == 0.25)

    print("\nsessions -- a failed capture falls back rather than failing the session")
    pipeline.capture_page = _fake_capture_fail
    fallback = run(session_routes.create_session(
        CreateSessionRequest(mode="url", target_url="https://unreachable.example"),
        alice_user, db))
    check("session still created when capture fails",
          fallback.id.startswith("ses_"))
    check("...and is flagged as a placeholder layout",
          fallback.layout_is_placeholder is True)
    fb_detail = run(session_routes.get_session(fallback.id, alice_user, db))
    check("the capture failure reason is kept",
          "TimeoutError" in fb_detail.capture_meta["reason"])

    pipeline.capture_page = _fake_capture_ok

    # ------------------------------------------------------------------
    print("\npipeline -- gaze is translated into the layout's coordinate system")
    # A document-scope layout describes the whole scrollable page; gaze arrives
    # relative to the viewport. Without this translation every point lands on
    # the first screen and everything below the fold reads as ignored.
    doc_meta = {"scope": "document", "viewport": [1280, 720],
                "document_size": [1280, 2880]}
    pts = [
        {"timestamp": 1.0, "x": 0.5, "y": 0.5, "scroll_y": 0},      # first screen
        {"timestamp": 2.0, "x": 0.5, "y": 0.5, "scroll_y": 2160},   # last screen
    ]
    moved, n_scrolled = pipeline.to_document_space(pts, doc_meta)
    check("one point carried a scroll offset", n_scrolled == 1)
    check("unscrolled gaze maps into the first quarter of the page",
          abs(moved[0]["y"] - (0.5 * 720) / 2880) < 1e-6)
    check("scrolled gaze maps far down the page",
          abs(moved[1]["y"] - (0.5 * 720 + 2160) / 2880) < 1e-6)
    check("the two land on different parts of the document",
          moved[1]["y"] > moved[0]["y"] + 0.7)
    check("translated coords stay in [0,1]",
          all(0.0 <= p["y"] <= 1.0 for p in moved))

    same, n2 = pipeline.to_document_space(pts, {"scope": "viewport"})
    check("viewport-scope layouts are left untouched",
          same[1]["y"] == 0.5 and n2 == 0)
    check("a test_ui session (no capture_meta) is untouched",
          pipeline.to_document_space(pts, None)[0][1]["y"] == 0.5)
    check("incomplete capture metadata is a no-op, not a crash",
          pipeline.to_document_space(pts, {"scope": "document"})[0][1]["y"] == 0.5)

    print("\nsessions -- ownership boundary")
    bob_session = run(session_routes.create_session(
        CreateSessionRequest(mode="test_ui", ui_page="form_page"), bob_user, db))

    expect_http("bob's session is invisible to alice",
                session_routes.get_session(bob_session.id, alice_user, db), 404)
    expect_http("alice cannot post gaze to bob's session",
                session_routes.append_gaze(
                    bob_session.id,
                    GazeBatchRequest(gaze=[{"timestamp": 1.0, "x": 0.5, "y": 0.5}]),
                    alice_user, db), 404)
    expect_http("alice cannot finalize bob's session",
                session_routes.finalize_session(bob_session.id, _Background(),
                                                alice_user, db), 404)
    expect_http("alice cannot read bob's report",
                session_routes.get_report(bob_session.id, __import__("fastapi").Response(),
                                          alice_user, db), 404)
    expect_http("alice cannot delete bob's session",
                session_routes.delete_session(bob_session.id, alice_user, db), 404)
    expect_http("a session id that never existed",
                session_routes.get_session("ses_nope", alice_user, db), 404)

    listing = run(session_routes.list_sessions(20, 0, None, alice_user, db))
    check("alice's list contains only her sessions",
          all(s.id != bob_session.id for s in listing.sessions))
    # test_ui + captured url + failed-capture fallback
    check("alice sees her three sessions", listing.total == 3)
    bob_listing = run(session_routes.list_sessions(20, 0, None, bob_user, db))
    check("bob sees only his one", bob_listing.total == 1)

    # ------------------------------------------------------------------
    print("\nsessions -- listing, pagination, filtering")
    for i in range(5):
        run(session_routes.create_session(
            CreateSessionRequest(mode="test_ui", ui_page="form_page",
                                 label=f"bulk {i}"), alice_user, db))
    page1 = run(session_routes.list_sessions(3, 0, None, alice_user, db))
    page2 = run(session_routes.list_sessions(3, 3, None, alice_user, db))
    check("total counts all sessions, not just the page", page1.total == 8)
    check("limit respected", len(page1.sessions) == 3)
    check("offset returns different rows",
          {s.id for s in page1.sessions}.isdisjoint({s.id for s in page2.sessions}))
    check("newest first",
          page1.sessions[0].created_at >= page1.sessions[-1].created_at)
    filtered = run(session_routes.list_sessions(20, 0, "created", alice_user, db))
    check("status filter applied", all(s.status == "created" for s in filtered.sessions))
    check("filter for an unused status is empty",
          run(session_routes.list_sessions(20, 0, "complete", alice_user, db)).total == 0)

    # ------------------------------------------------------------------
    print("\nsessions -- calibration link trains a real gaze model")
    from calibration.storage import CalibrationStore, set_store
    from gaze_estimation import set_model_dir
    from gaze_estimation.synthetic import generate_calibration_session
    import gaze_estimation.training as ge_training

    cal_dir = _TMP / "calibration"
    model_dir = _TMP / "models"
    store = CalibrationStore(data_dir=cal_dir)
    set_store(store)
    set_model_dir(model_dir)
    ge_training.MODEL_DIR = model_dir

    cal_session = generate_calibration_session(pattern=16, samples_per_point=12,
                                               participant_id="alice", seed=11)
    store.save(cal_session)

    linked = run(session_routes.link_calibration(
        session_id, CalibrationLinkRequest(calibration_session_id=cal_session.session_id),
        alice_user, db))
    check("calibration linked", linked.calibration_session_id == cal_session.session_id)
    check("status advanced to calibrated", linked.status == "calibrated")
    check("gaze model actually trained", linked.gaze_model_trained is True)
    check("training reported held-out error",
          linked.gaze_model_metrics["median_error_px"] > 0)
    check("calibration quality surfaced", linked.calibration["usable"] is True)
    print(f"        gaze model: {linked.message}")

    expect_http("linking a calibration that doesn't exist",
                session_routes.link_calibration(
                    session_id, CalibrationLinkRequest(calibration_session_id="cal_nope"),
                    alice_user, db), 404)

    detail = run(session_routes.get_session(session_id, alice_user, db))
    check("detail exposes the calibration summary", detail.calibration is not None)
    check("detail tells the client what to do next", detail.next_action == "record")

    # ------------------------------------------------------------------
    print("\nsessions -- gaze ingestion")
    expect_http("finalizing with no gaze",
                session_routes.finalize_session(session_id, _Background(),
                                                alice_user, db), 422)

    from attribution import synthetic as attr_syn

    gaze_samples, _cfg = attr_syn.ignored_cta_session()
    payload = [{"timestamp": s.timestamp, "x": s.x, "y": s.y,
                "valid": s.valid, "confidence": s.confidence} for s in gaze_samples]

    first = run(session_routes.append_gaze(
        session_id, GazeBatchRequest(gaze=payload[:100]), alice_user, db))
    check("first batch accepted", first.accepted == 100)
    check("status moved to recording", first.status == "recording")
    second = run(session_routes.append_gaze(
        session_id, GazeBatchRequest(gaze=payload[100:]), alice_user, db))
    check("batches accumulate", second.total_points == len(payload))

    stored = pipeline.read_gaze(pipeline.gaze_path_for(DATA_DIR, session_id))
    check("gaze round-trips through the JSONL file", len(stored) == len(payload))
    check("invalid points are preserved, not filtered",
          sum(1 for p in payload if not p["valid"])
          == sum(1 for p in stored if not p["valid"]))

    print("\nreport -- 202 while pending")
    import fastapi

    pending = run(session_routes.get_report(session_id, fastapi.Response(),
                                            alice_user, db))
    check("no report yet", pending.ready is False)
    check("pending tells the client what to do", pending.next_action == "finalize")

    # ------------------------------------------------------------------
    print("\nEND TO END -- finalize runs attribution -> agents -> reports")
    bg = _Background()
    fin = run(session_routes.finalize_session(session_id, bg, alice_user, db))
    check("finalize returns immediately", fin.status == "processing")
    check("analysis was scheduled as a background task", "_run_analysis" in bg.ran)

    db.expire_all()
    final = run(session_routes.get_session(session_id, alice_user, db))
    check("session reached a terminal status", final.status in ("complete", "failed"))
    if final.status == "failed":
        print(f"        FAILURE: {final.error}")
    check("session completed successfully", final.status == STATUS_COMPLETE)
    check("completion timestamp set", final.completed_at is not None)
    check("has_report is now true", final.has_report is True)

    report = run(session_routes.get_report(session_id, fastapi.Response(),
                                           alice_user, db))
    check("report returned", report.report_id.startswith("rep_"))

    print("\nreport -- the agents' output is passed through unreshaped")
    pr = report.pipeline_result
    check("pipeline_result keeps orchestrator's keys",
          {"session_id", "behavior_summary", "issues",
           "recommendations_kept", "recommendations_rejected"} <= set(pr))
    findings = {f["finding_type"] for f in pr["behavior_summary"]["findings"]}
    print(f"        CTA dwell {report.metrics['dwell_time']['checkout_button']:.2f}s "
          f"of {report.metrics['total_gaze_time']:.1f}s -> {sorted(findings)}")
    check("the ignored-CTA scenario produced findings", len(findings) > 0)
    check("delayed discovery detected end-to-end", "delayed_discovery" in findings)
    check("metrics match the agents' SessionMetrics shape",
          {"dwell_time", "ttff", "fixation_count", "revisit_count",
           "total_gaze_time", "scanpath"} <= set(report.metrics))
    check("ui_page carried through", report.ui_page == "ecommerce_product_page")
    check("test_ui report carries no placeholder warning",
          report.layout_is_placeholder is False)

    print("\nreport -- rendered artefacts")
    check("heatmap written", report.heatmap_path and Path(report.heatmap_path).exists())
    check("HTML written", report.html_path and Path(report.html_path).exists())
    if report.pdf_path and Path(report.pdf_path).exists():
        size = Path(report.pdf_path).stat().st_size
        print(f"        PDF via {report.pdf_backend}: {size:,} bytes")
        check("PDF is a real PDF",
              Path(report.pdf_path).read_bytes()[:5] == b"%PDF-")
    else:
        check("PDF absent but the analysis survived", report.metrics is not None)
        print("        (no PDF backend on this machine -- analysis unaffected)")

    print("\nsessions -- finalize is not repeatable")
    expect_http("finalizing a session that already has a report",
                session_routes.finalize_session(session_id, _Background(),
                                                alice_user, db), 409)
    expect_http("posting gaze to a completed session",
                session_routes.append_gaze(
                    session_id, GazeBatchRequest(gaze=[{"timestamp": 1, "x": 0.5, "y": 0.5}]),
                    alice_user, db), 409)

    # ------------------------------------------------------------------
    print("\nsessions -- failure is terminal and explained")
    broken = run(session_routes.create_session(
        CreateSessionRequest(mode="test_ui", ui_page="form_page", label="broken"),
        alice_user, db))
    run(session_routes.append_gaze(
        broken.id, GazeBatchRequest(gaze=[{"timestamp": 1.0, "x": 0.5, "y": 0.5}]),
        alice_user, db))
    # One gaze point can't be analysed -- attribution needs a stream.
    db_obj = db.get(SessionModel, broken.id)
    db_obj.element_layout = {}          # unusable layout, forces a failure
    db.commit()
    run(session_routes.finalize_session(broken.id, _Background(), alice_user, db))
    db.expire_all()
    broken_detail = run(session_routes.get_session(broken.id, alice_user, db))
    check("a failing analysis lands on 'failed', not stuck on 'processing'",
          broken_detail.status == "failed")
    check("the failure reason is recorded", bool(broken_detail.error))
    failed_report = run(session_routes.get_report(broken.id, fastapi.Response(),
                                                  alice_user, db))
    check("report endpoint explains the failure",
          failed_report.ready is False and "failed" in failed_report.message)

    # ------------------------------------------------------------------
    print("\nsessions -- url-mode reports say their labels were auto-detected")
    run(session_routes.append_gaze(
        url_session.id, GazeBatchRequest(gaze=payload[:200]), alice_user, db))
    run(session_routes.finalize_session(url_session.id, _Background(), alice_user, db))
    db.expire_all()
    url_report = run(session_routes.get_report(url_session.id, fastapi.Response(),
                                               alice_user, db))
    check("url session produced a report", getattr(url_report, "report_id", None))
    check("a captured layout is not flagged as a placeholder",
          url_report.layout_is_placeholder is False)
    check("but the report still says the labels were auto-detected",
          any("auto-detected" in w for w in url_report.warnings))
    check("and quotes how much was guessed",
          any("25%" in w for w in url_report.warnings))

    print("\nsessions -- a fallback report DOES carry the placeholder warning")
    run(session_routes.append_gaze(
        fallback.id, GazeBatchRequest(gaze=payload[:200]), alice_user, db))
    run(session_routes.finalize_session(fallback.id, _Background(), alice_user, db))
    db.expire_all()
    fb_report = run(session_routes.get_report(fallback.id, fastapi.Response(),
                                              alice_user, db))
    check("fallback report flags placeholder boxes",
          fb_report.layout_is_placeholder is True)
    check("and says so in capitals, with the reason",
          any("PLACEHOLDER" in w and "TimeoutError" in w for w in fb_report.warnings))

    pipeline.capture_page = _real_capture

    # ------------------------------------------------------------------
    print("\nsessions -- deletion")
    gaze_file = Path(pipeline.gaze_path_for(DATA_DIR, session_id))
    check("gaze file exists before deletion", gaze_file.exists())
    run(session_routes.delete_session(session_id, alice_user, db))
    db.expire_all()
    check("session row gone", db.get(SessionModel, session_id) is None)
    check("report cascaded away",
          db.query(Report).filter(Report.session_id == session_id).count() == 0)
    check("gaze file cleaned up", not gaze_file.exists())
    expect_http("deleting twice",
                session_routes.delete_session(session_id, alice_user, db), 404)

    db.close()

finally:
    try:
        from calibration.storage import set_store as _reset_store

        _reset_store(None)
    except Exception:                      # noqa: BLE001
        pass
    warnings.filterwarnings("ignore")
    shutil.rmtree(_TMP, ignore_errors=True)


print(f"\n{'=' * 40}\n{passed} passed, {failed} failed\n{'=' * 40}")

if failed:
    raise SystemExit(1)
