"""
generate_api_client.py

Writes two things the frontend team can work against:

    frontend/src/api/openapi.json          machine-readable spec
    frontend/src/api/client.generated.js   a working JS client

    python scripts/generate_api_client.py

WHY THIS EXISTS
---------------
The real frontend/src/api/client.js has never been pushed to this repo, so the
session API's request/response shapes were defined server-side rather than
matched to it (see backend/api/CONTRACT.md).

This does NOT overwrite client.js. It writes client.generated.js next to it,
so whoever holds the real client can DIFF the two and see exactly where the
backend disagrees with their mocks -- which is the actual blocker, and is not
something a hand-written description resolves.

Regenerate after changing any route or schema; the spec is derived from the
running app, so it cannot drift from the code the way prose does.
"""

import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
OUT_DIR = REPO / "frontend" / "src" / "api"

HEADER = """// AUTO-GENERATED by scripts/generate_api_client.py -- do not edit by hand.
//
// This is NOT the app's client.js. It is a reference implementation generated
// from the FastAPI app's OpenAPI spec, so the frontend team can diff it
// against the real client and see exactly where the two contracts disagree.
//
// Regenerate with:  python scripts/generate_api_client.py
"""

CLIENT_BODY = """
const BASE_URL = import.meta?.env?.VITE_API_URL ?? "http://localhost:8000";

const TOKEN_KEY = "gazelens_token";

export function getToken() {
  return localStorage.getItem(TOKEN_KEY);
}

export function setToken(token) {
  if (token) localStorage.setItem(TOKEN_KEY, token);
  else localStorage.removeItem(TOKEN_KEY);
}

export class ApiError extends Error {
  constructor(status, detail) {
    // FastAPI returns {detail: "..."} for HTTPException and
    // {detail: [{loc, msg, ...}]} for validation errors. Flatten both so a
    // caller can always just show error.message.
    const text = Array.isArray(detail)
      ? detail.map((d) => `${(d.loc || []).join(".")}: ${d.msg}`).join("; ")
      : String(detail ?? `HTTP ${status}`);
    super(text);
    this.name = "ApiError";
    this.status = status;
    this.detail = detail;
  }
}

async function request(method, path, { body, auth = true, query } = {}) {
  const url = new URL(BASE_URL + path);
  if (query) {
    for (const [k, v] of Object.entries(query)) {
      if (v !== undefined && v !== null) url.searchParams.set(k, v);
    }
  }

  const headers = {};
  if (body !== undefined) headers["Content-Type"] = "application/json";
  if (auth) {
    const token = getToken();
    if (token) headers["Authorization"] = `Bearer ${token}`;
  }

  const res = await fetch(url, {
    method,
    headers,
    body: body === undefined ? undefined : JSON.stringify(body),
  });

  if (res.status === 204) return null;

  const payload = await res.json().catch(() => null);
  if (!res.ok) throw new ApiError(res.status, payload?.detail);

  // 202 on the report endpoint means "not ready yet", not an error. The
  // status is attached so callers can poll instead of treating it as a
  // finished report.
  if (res.status === 202) return { ...payload, _pending: true };
  return payload;
}

// --- auth -----------------------------------------------------------------

export async function signup(email, password) {
  const data = await request("POST", "/api/auth/signup", {
    body: { email, password },
    auth: false,
  });
  setToken(data.access_token);
  return data;
}

export async function login(email, password) {
  const data = await request("POST", "/api/auth/login", {
    body: { email, password },
    auth: false,
  });
  setToken(data.access_token);
  return data;
}

export function logout() {
  setToken(null);
}

export function me() {
  return request("GET", "/api/auth/me");
}

// --- sessions -------------------------------------------------------------

export function createSession({ mode = "test_ui", uiPage, targetUrl, label,
                                calibrationSessionId } = {}) {
  return request("POST", "/api/sessions", {
    body: {
      mode,
      ui_page: uiPage,
      target_url: targetUrl,
      label,
      calibration_session_id: calibrationSessionId,
    },
  });
}

export function listSessions({ limit = 20, offset = 0, status } = {}) {
  return request("GET", "/api/sessions", { query: { limit, offset, status } });
}

export function getSession(sessionId) {
  return request("GET", `/api/sessions/${sessionId}`);
}

export function deleteSession(sessionId) {
  return request("DELETE", `/api/sessions/${sessionId}`);
}

export function listTestUis() {
  return request("GET", "/api/sessions/meta/test-uis");
}

export function linkCalibration(sessionId, calibrationSessionId,
                                trainModel = true) {
  return request("POST", `/api/sessions/${sessionId}/calibration`, {
    body: {
      calibration_session_id: calibrationSessionId,
      train_model: trainModel,
    },
  });
}

/**
 * Append a batch of gaze points.
 *
 * IMPORTANT: send invalid points (blinks) too -- the backend needs the gap to
 * tell a blink from a glance away. And on a scrollable page, send scroll_y
 * with every point, or everything below the fold will read as unlooked-at.
 */
export function appendGaze(sessionId, gaze) {
  return request("POST", `/api/sessions/${sessionId}/gaze`, { body: { gaze } });
}

export function finalizeSession(sessionId) {
  return request("POST", `/api/sessions/${sessionId}/finalize`);
}

/** Resolves to the report, or {_pending: true, status, message} if not ready. */
export function getReport(sessionId) {
  return request("GET", `/api/sessions/${sessionId}/report`);
}

/** Poll until the report is ready, or throw after `timeoutMs`. */
export async function waitForReport(sessionId, { intervalMs = 2000,
                                                 timeoutMs = 120000 } = {}) {
  const deadline = Date.now() + timeoutMs;
  for (;;) {
    const report = await getReport(sessionId);
    if (!report._pending) return report;
    if (report.status === "failed") {
      throw new ApiError(500, report.message);
    }
    if (Date.now() > deadline) {
      throw new ApiError(504, `report not ready after ${timeoutMs}ms`);
    }
    await new Promise((r) => setTimeout(r, intervalMs));
  }
}

// --- calibration ----------------------------------------------------------

export function startCalibration({ participantId, pattern = 16,
                                   screenWidth, screenHeight,
                                   samplesPerPoint }) {
  return request("POST", "/api/calibration/sessions", {
    body: {
      participant_id: participantId,
      pattern,
      screen_width: screenWidth,
      screen_height: screenHeight,
      samples_per_point: samplesPerPoint,
    },
  });
}

export function submitCalibrationFrames(calibrationSessionId, pointIndex,
                                        frames) {
  return request(
    "POST", `/api/calibration/sessions/${calibrationSessionId}/samples`,
    { body: { point_index: pointIndex, frames } },
  );
}

export function completeCalibration(calibrationSessionId) {
  return request(
    "POST", `/api/calibration/sessions/${calibrationSessionId}/complete`);
}

// --- gaze estimation ------------------------------------------------------

export function estimateGaze(calibrationSessionId, { left, right, timestamp,
                                                     confidence = 1.0 }) {
  return request(
    "POST", `/api/gaze/models/${calibrationSessionId}/estimate`,
    { body: { left, right, timestamp, confidence } },
  );
}

// --- render ---------------------------------------------------------------

export function capturePage(url, { viewportWidth, viewportHeight } = {}) {
  return request("POST", "/api/render/capture", {
    body: {
      url,
      viewport_width: viewportWidth,
      viewport_height: viewportHeight,
    },
  });
}

export function health() {
  return request("GET", "/health", { auth: false });
}
"""


def main() -> int:
    sys.path.insert(0, str(REPO / "backend"))
    try:
        from api.main import app
    except Exception as exc:            # noqa: BLE001
        print(f"could not import the FastAPI app: {type(exc).__name__}: {exc}")
        return 1

    OUT_DIR.mkdir(parents=True, exist_ok=True)

    spec = app.openapi()
    spec_path = OUT_DIR / "openapi.json"
    spec_path.write_text(json.dumps(spec, indent=2), encoding="utf-8")

    client_path = OUT_DIR / "client.generated.js"
    routes = sorted(
        f"{m.upper()} {p}"
        for p, ops in spec["paths"].items() for m in ops
    )
    listing = "\n".join(f"//   {r}" for r in routes)
    client_path.write_text(
        f"{HEADER}//\n// Endpoints in this build:\n{listing}\n{CLIENT_BODY}",
        encoding="utf-8",
    )

    print(f"wrote {spec_path.relative_to(REPO)}  ({len(spec['paths'])} paths)")
    print(f"wrote {client_path.relative_to(REPO)}")
    print("\nThis does NOT touch client.js. Diff the two to find where the "
          "backend and the frontend's mocks disagree.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
